-- 1.  How many Restaurant have a rating greater than  4.5?
select count(Restaurant) from swiggy_data where Avg_ratings>4.5;

-- 2. which restaurant have more Avg_ratings in bangalore city?
select city,Restaurant,Avg_ratings from swiggy_data
where city='Bangalore' order by Avg_ratings desc limit 1;

-- 3.  Restaurants with maximum delivery time and minimum delivery time

select  Restaurant,city, max(Delivery_time) from swiggy_data group by Restaurant,city order by max(Delivery_time) desc limit 28 ;
-- 28 restaurants  are from the city kolkata  
select  Restaurant,city, min(Delivery_time) from swiggy_data group by Restaurant,city order by min(Delivery_time)  limit 10;


-- 4 . which  city have highest number of Restaurants?
select city,count(Restaurant) as restaurent_count from swiggy_data
group by city
order by restaurent_count desc
limit 1;


--  5.Find the address in each city in which maximum order takes place

select Address ,count(Address),city from swiggy_data
group by Address,city 
order by count(Address) desc ;
--  In Delhi address rohini has the highest order delivered with a count of 229

-- 6. .Most Expensive Restaurants
select Restaurant, Price
from swiggy_data
order by Price desc
limit 10;

-- 7.Restaurants with the Most Reviews
select Restaurant, Total_ratings
from swiggy_data
order by Total_ratings desc
limit 10;

-- 8 .create a view table and that shows the count of city?
create view City_Counts as select City,count(City) from swiggy group by City;
select * from City_Counts;

-- 9.   Find the areas with most number of restaurants and least number of restaurants
select area,city ,count(Restaurant) from swiggy_data
group by area,city 
order by count(Restaurant) desc 
limit 5;
--  In delhi Rohini area has the highest no of restaurants
select area,city ,count(Restaurant) from swiggy_data
group by area,city 
order by count(Restaurant) 
limit 5;

-- 10. which restaurent has more rating in each city?
select city,restaurant, avg_ratings from swiggy_data
having Avg_ratings=(select max(Avg_ratings) from swiggy_data) order by City; 

-- 11. Number of restaurants in each city serving indian food
select city, count(Restaurant) from swiggy_data  where Food_type like 'indian'group by city  order by count(Restaurant) desc  ;
-- Kolkata at the top and surat at the last 

-- 12.  Average delivery time by city
select city,round(avg(Delivery_time),0)  as avg_delivery_time from swiggy_data group by city order by round(avg(Delivery_time),0)  ;
-- Average delivery time of these cities is more than 45 minutes and the value range from 45 to 68 minutes

-- 13.Top 20 Rated Restaurants

select Restaurant, Avg_ratings, Total_ratings
from swiggy_data
order by Avg_ratings desc
limit 20;

-- 14. What is the average total rating for restaurants in each price range
 
 SELECT 
    CASE 
        WHEN price < 500 THEN 'Low'
        WHEN price >= 500 and price < 2000 THEN 'Medium'
        ELSE 'High'
    END AS price_range,
    round(avg(Total_ratings),0)AS avg_total_rating
FROM 
    swiggy_data
GROUP BY price_range; 



-- 15. Percentage of  revenue generated by each city
 select city, sum(price) as total_price,round(sum(price)/(select sum(price) 
from swiggy_data)*100,2) as total_percentage 
from swiggy_data group by city order by sum(price) desc ;